using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// Controla el cambio entre la cámara orbital y la de primera persona,
/// y maneja los distintos "focos" de la cámara orbital (toda la escena / objeto puntual).
///
/// Setup en el Inspector:
///  - Arrastrar la Camera orbital y la Camera FPS (cada una con su script correspondiente).
///  - En "Focus Targets" arrastrar los Transforms de los objetos importantes de la Escena B
///    (ej: mesa, tetera principal, jarrón, etc.).
///  - En "Focus Distances" poner, en el mismo orden, la distancia de cámara apropiada para cada uno.
///
/// Controles:
///  - Tab           -> alterna entre cámara orbital y primera persona
///  - 0              -> (en modo orbital) enfoca toda la escena
///  - 1,2,3...       -> (en modo orbital) enfoca el objeto correspondiente de la lista
/// </summary>
public class CameraManagerb2 : MonoBehaviour
{
    [Header("Cámaras")]
    public Camera orbitalCamera;
    public OrbitalCamera orbitalScript;
    public Camera firstPersonCamera;

    [Header("Objetos importantes para enfocar")]
    public List<Transform> focusTargets = new List<Transform>();
    public List<float> focusDistances = new List<float>();

    private Transform sceneCenter;
    private float sceneFitDistance;

    void Start()
    {
        CalculateSceneBounds();
        SwitchToOrbital();
        FocusWholeScene();
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Tab))
        {
            if (orbitalCamera.enabled) SwitchToFirstPerson();
            else SwitchToOrbital();
        }

        if (orbitalCamera.enabled)
        {
            if (Input.GetKeyDown(KeyCode.Alpha0)) FocusWholeScene();

            for (int i = 0; i < focusTargets.Count && i < 9; i++)
            {
                if (Input.GetKeyDown(KeyCode.Alpha1 + i))
                {
                    float dist = (i < focusDistances.Count) ? focusDistances[i] : 5f;
                    orbitalScript.SetTarget(focusTargets[i], dist);
                }
            }
        }
    }

    void SwitchToOrbital()
    {
        orbitalCamera.enabled = true;
        firstPersonCamera.enabled = false;

        SetAudioListener(orbitalCamera, true);
        SetAudioListener(firstPersonCamera, false);
    }

    void SwitchToFirstPerson()
    {
        firstPersonCamera.enabled = true;
        orbitalCamera.enabled = false;

        SetAudioListener(firstPersonCamera, true);
        SetAudioListener(orbitalCamera, false);
    }

    void SetAudioListener(Camera cam, bool state)
    {
        AudioListener listener = cam.GetComponent<AudioListener>();
        if (listener != null) listener.enabled = state;
    }

    void CalculateSceneBounds()
    {
        Renderer[] renderers = FindObjectsOfType<Renderer>();
        if (renderers.Length == 0) return;

        Bounds bounds = renderers[0].bounds;
        foreach (Renderer r in renderers)
            bounds.Encapsulate(r.bounds);

        GameObject centerObj = new GameObject("SceneCenter_AutoGenerated");
        centerObj.transform.position = bounds.center;
        sceneCenter = centerObj.transform;

        // Distancia aproximada para que la escena completa entre en cámara
        sceneFitDistance = bounds.size.magnitude * 1.2f;
    }

    void FocusWholeScene()
    {
        orbitalScript.SetTarget(sceneCenter, sceneFitDistance);
    }
}